### ISSUE TITLE
Autosubmit images for scanning with anchore-engine open-source

### ISSUE THREAD

**Issue by kroussou** [anchore/kai#25]
**What would you like to be added**:
Add option to use `/images` API endpoint (and maybe `/subscriptions`, if needed) instead of `enterprise/inventories`

**Why is this needed**:
As a result kai will submit images for scanning as soon as they start to be used in a cluster. 

This will make kai more useful for anchore-engine open-source users.

**Comment by hev** [comment]
@kroussou thanks for the submission. At the moment we don't have immediate plans to connect kai directly to engine as runtime is a key value add for our enterprise customers. We are certainly open to users doing so in the community. We want to keep kai as simple as possible so our preference would be to keep the existing API output and have other tools to pipe and manipulate the output. I could see making the endpoint configurable instead of tying it to `/enterprise/inventories` but we are unlikely to prioritize work beyond that right now. 

cc @zhill @dakaneye

**Comment by ArjonBu** [comment]
@hev actually that would be a very important feature for enterprise users too.
